### ISSUE TITLE
add forest gap model

### ISSUE THREAD

**Issue by fdschneider** [fdschneider/caspr#11]

**Comment by alexgenin** [comment]
Done in ./R/forestgap.R, but deserves some more testing when the suite is complete.

See also:
https://github.com/skefi/SpatialStress/wiki/forestgap

**Comment by alexgenin** [comment]
Added tests today and found a bug ! Forestgap produces good results now. 

See also:
https://github.com/skefi/SpatialStress/wiki/forestgap
