### ISSUE TITLE
Error during installation of caspr package

### ISSUE THREAD

**Issue by alaindanet** [fdschneider/caspr#13]
The dependencies "spatialwarnings" is not found. May be it's just because the name of the actual repository is "spatial_warnings".

**Comment by alexgenin** [comment]
You need to install it explicitely using devtools first, otherwise document() tries to install it from CRAN: 

```
devtools::install_github('fdschneider/spatial_warnings')
```

**Comment by fdschneider** [comment]
Seems so. That is why I tried to specify an additional repository to look it up. But that does not work apparently. Any suggestions are welcome.

**Comment by alaindanet** [comment]
Okay, I just removed the spatial warnings dependencie but now a new error happens during the installation. It justs some help files are missing.

**Comment by fdschneider** [comment]
I think this was caused because the functions and model objects were not added to the NAMESPACE.
I think this is fixed, but could you verify, please @alaindanet?

**Comment by alaindanet** [comment]
It works now!
