### ISSUE TITLE
dynamic setting of snapshots and min-max timesteps in `ca()`

### ISSUE THREAD

**Issue by fdschneider** [fdschneider/caspr#14]

**Comment by alaindanet** [comment]
Okay, I just try to set up some conditions to be sure it cans work. For example, be sure that t_min-2*t_eval is superior to 0.

**Comment by alaindanet** [comment]
Flo, is it okay for you if I work on this issue ? I have just seen that when I assigned myself to this issue, I unassigned you.

**Comment by fdschneider** [comment]
sure. thats fine. The tricky part is the interplay of t_eval and the setting of the snapshots, because they are only saved every nth timestep. 
If stability is reached, the simulation still needs to run until a minimal number of snapshots are collected. 

Maybe, it would be easier to additionally ask for n_snaps in the function arguments, to know beforehand how many snaps should be stored, independently of t_eval.

**Comment by alaindanet** [comment]
Okay. I got your point. Furthermore it's may be more important for our comparaison methods to have a fixed number of snapshots rather than have regular timesteps to save.

**Comment by fdschneider** [comment]
Well, we need both. The distance between snapshots must be equal and at least 50 for evaluation of spatial indicators. But to plot an animation of the cellular automata I would like to be able to run the model with saveeach = 1, or 2.

**Comment by fdschneider** [comment]
@alaindanet: Did you make any progress here? I would work on it myself a little. I have an idea.

**Comment by fdschneider** [comment]
I redefined steadyness to be checked only at the times where snapshots are taken. If steady state is not reached, the simulation runs to the next snapshot, that is another `saveeach` timesteps, before it checks again.  `t_max` is superior and terminates the simulation in any case.
