### ISSUE TITLE
Fix dependencies on non-CRAN packages (hosted at GitHub)

### ISSUE THREAD

**Issue by fdschneider** [fdschneider/caspr#15]
The package depends on other repositories that are not hosted at CRAN
- ['fdschneider/spatial_warnings'](https://github.com/fdschneider/spatial_warnings) which is my attempt to wrap the spatial_warnings code into a working R package and which is hosted on GitHub
- ['EBImage'](http://www.bioconductor.org/packages/release/bioc/html/EBImage.html) which provides some functions for measuring patch size and perimeter and is hosted on Bioconductor. 

The dependency for the first does seem to cause problems during instalation of the package (see #13).  
The installation for the latter can be problematic because of its own dependencies (see #4) and that is why I did not use it so far. As a side note, the Bioconductor packages are also hosted on GitHub at https://github.com/Bioconductor-Mirror. This might be easier to install than from Bioconductor.

**Comment by alaindanet** [comment]
I think that the best option would be to put those packages as suggested in the DESCRIPTION file and put a loading/installation command in the functions which depends on packages hosted on Github.

**Comment by alaindanet** [comment]
For now, I just removed spatial_warnings from dependencies

**Comment by fdschneider** [comment]
This should count as **solved** until we put it back in. Can you install the package now from GitHub on a virgin R install?

**Comment by alaindanet** [comment]
It's okay, it works now!
