### ISSUE TITLE
function for patch size fitting

### ISSUE THREAD

**Issue by fdschneider** [fdschneider/caspr#2]
function input:
- vector of integer patch sizes

**Comment by fdschneider** [comment]
@ssumithra I remember we said that you will provide a function for that? However, a working function is now implemented in R. Maybe we can check the validity by comparing the output to your function.

**Comment by ssumithra** [comment]
Yes yes yes. We should check this. Also, my area-perimeter code calculates
the patch distribution anyway (because the perimeter of each patch needs to
be tied to its are). So we may want to see if we want to do away with this
double calculation, and if so how, etc..

**Comment by guttal** [comment]
Yes, it makes sense to calculate patch-sizes only once, keep in an array/equivalent, and use it for both area-permimeter and distribution calculations.

**Comment by fdschneider** [comment]
There is also a function included in the spatial_warnings package. 

Then  for now, let's just include all our candidate functions in `patches.R`.  I will compare them in a benchmark test and chose the fastest and safest. 
For compatibility the functions should:
- assume periodic boundaries (, right ?)
- take a landscape _or_ matrix object as input
- return a vector of patch sizes

**Comment by fdschneider** [comment]
This is an [issue at 'spatial_warnings' package](https://github.com/fdschneider/spatial_warnings/issues/2) now.
