### ISSUE TITLE
write package vignette

### ISSUE THREAD

**Issue by fdschneider** [fdschneider/caspr#26]

**Comment by fdschneider** [comment]
Not sure how this works. I just copied the README into a .Rmd file. It is supposed to be built into a html and pdf file during package building.

**Comment by alaindanet** [comment]
I did a commit to put the YALM as in the Hadley Wickham book. Now, it works. 
You can also check by doing:

```
install_github("fdschneider/caspr", build_vignettes=T)
vignette("caspr")
```
