### ISSUE TITLE
make carray() work with a non-package ca_model object. 

### ISSUE THREAD

**Issue by fdschneider** [fdschneider/caspr#28]
If specifying an own ca_model object it is straightforward to run `ca()` with it. 

```
ca(l, own)
```

However, if using `carray()` the foreach loop breaks and cannot access the object provided. I guess it needs to be sourced to the worker environment.

**Comment by alexgenin** [comment]
For this I usually use clusterExport. I guess we could add a (untested)

``` r
clusterExport('model', envir=environment())
```

somewhere in carray.

**Comment by fdschneider** [comment]
Thanks, your comment gave me the right search terms. Its even easier by adding `.export = c("model")` to the foreach call. 

However it seems it is just an issue with my way of invoking the parallel backend in Linux. I was using doSNOW which apparently creates workers with incomplete environments. doMC works better.
