### ISSUE TITLE
Add an `as.binary_matrix` method for `ca_run` objects

### ISSUE THREAD

**Issue by alexgenin** [fdschneider/caspr#32]
Do not forget to add an `as.binary_matrix` method for `ca_run` objects.

**Comment by fdschneider** [comment]
First of all, we need that for `landscape` objects. I have done that already. I just need to rename it and test. For `ca_run` objects, the function should return a list of `binary_matrix` objects with all the landscape objects stored in `$landscapes`, right?

**Comment by fdschneider** [comment]
done. Commit: e5fc5beb8e8da022875db0e38e35780e79ef9f2a
