### ISSUE TITLE
build and add manual.pdf

### ISSUE THREAD

**Issue by fdschneider** [fdschneider/caspr#33]
We should build and upload the manual (i.e. the complete documentation of all functions) as a separate pdf file for download. Is there an automated workflow for package distribution on Github that builds the documentation?

**Comment by alexgenin** [comment]
Good question. A quick search provides [this result](http://stackoverflow.com/questions/30607496/making-an-r-package-pdf-manual-using-devtools) but you have to install the package first. We could automate that with a shell script maybe.

Another option might be to retrieve it from R-forge once caspr actually builds without errors there.

**Comment by fdschneider** [comment]
Well, that workaround on stackoverflow looks promising but it did produce the following error on my PC: 

``` r
pack <- "name_of_your_package"
path <- find.package(pack)
system(paste(shQuote(file.path(R.home("bin"), "R")),
    "CMD", "Rd2pdf", shQuote(path)))
```

```
Hmm ... looks like a package
Converting parsed Rd's to LaTeX ..
Creating pdf output from LaTeX ...
Warning: running command '"C:\PROGRA~1\MIKTEX~1.9\miktex\bin\x64\texi2dvi.exe"  --pdf "Rd2.tex" --max-iterations=20 -I "C:/R/R-32~1.2/share/texmf/tex/latex" -I "C:/R/R-32~1.2/share/texmf/bibtex/bst"' had status 1
Error : running 'texi2dvi' on 'Rd2.tex' failed

LaTeX errors:
!pdfTeX error: pdflatex.EXE (file ts1-zi4r): Font ts1-zi4r at 540 not found
 ==> Fatal error occurred, no output PDF file produced!

Warning: running command '"C:\PROGRA~1\MIKTEX~1.9\miktex\bin\x64\texi2dvi.exe"  --pdf "Rd2.tex" --max-iterations=20 -I "C:/R/R-32~1.2/share/texmf/tex/latex" -I "C:/R/R-32~1.2/share/texmf/bibtex/bst"' had status 1
Error : running 'texi2dvi' on 'Rd2.tex' failed

LaTeX errors:
!pdfTeX error: pdflatex.EXE (file ts1-zi4r): Font ts1-zi4r at 540 not found
 ==> Fatal error occurred, no output PDF file produced!

Error in running tools::texi2pdf()
Warning message:
running command '"C:/R/R-32~1.2/bin/x64/R" CMD Rd2pdf "C:/R/R-3.2.2/library/caspr"' had status 1 
```

Looks like I am missing some dependencies for the pdf conversion. I think this can be solved. Will investigate. Does this work in Linux environment?  

If I run 'check package' in RStudio  (= `devtools::check`, i guess )  the full package including the manual is built in a separate directory and the pdf can be copied manually into the inst/doc/ directory. Thats fine for now I guess.

**Comment by fdschneider** [comment]
Nice! I found how to fix that missing font error for windows [in this post](http://tex.stackexchange.com/questions/125274/error-font-ts1-zi4r-at-540-not-found/129523#129523). Now the pdf is supposed to be created by running `R CMD Rd2pdf caspr`  from command line. The extra option `-o` defines output file name. Thus I modified the R Script: 

``` r
pack <- "caspr"
path <- find.package(pack)
wd <- getwd()
system(paste0(shQuote(file.path(R.home("bin"), "R")), 
   " CMD", " Rd2pdf --force -o ", wd ,"/inst/doc/caspr-manual.pdf ", 
   shQuote(path))
)
```
